<a href="https://colab.research.google.com/github/ssubbinn/ESAA/blob/main/2%EC%A3%BC%EC%B0%A8_%EA%B3%BC%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

CHAPTER 1 파이썬 기반의 머신러닝과 생태계 이해
1. 머신러닝의 개념

머신러닝 : 애플리케이션을 수정하지 않고도 데이터를 기반으로 패턴을 학습하고 결과를 예측하는 알고리즘 기법

<머신러닝 분류>

지도학습 : 분류, 회귀, 추천 시스템, 시각/음성 감지/인지, 텍스트 분석,NLP

비지도학습 : 클러스터링, 차원 축소, 강화학습

3. 넘파이

- 넘파이 array()함수는 파이썬의 리스트와 같은 다양한 인자를 입력 받아서 ndarray로 변환하는 기능을 수행

- 생성된 ndarray 배열의 shape 변수는 행과 열의 수를 튜플 형태로 가져 배열의 차원까지 알 수 있음

In [2]:
import numpy as np

In [ ]:
import numpy as np
array1 = np.array([1, 2, 3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1, 2, 3],
                  [2, 3, 4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1, 2, 3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [ ]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


ndarray의 데이터 타입

- 숫자, 문자열, 불 값 등 모두 가능

- 같은 데이터 타입만 연산 가능 (int는 int끼리, 리스트와 다른점)  

In [ ]:
list1=[1,2,3]
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [ ]:
#int형과 float형이 섞여 있는 리스트를 ndarray로 변경
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3=[1,2,3.0]
array3=np.array(list3)
print(array3,array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [ ]:
#astype() 이용 타입 변경 - 메모리 절약 가능
array_int= np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1= array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


ndarray를 편리하게 생성하기 - arange, zeros, ones

- 주로 테스트용으로 데이터를 만들거나 대규모의 데이터를 일괄적으로 초기화해야 할 경우에 사용

In [ ]:
#arange array를 range()로 표혀
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [3]:
#zeors() 모든 값을 0으로 채운 ndarray 반환
zero_array = np.zeros((3,2),dtype = 'int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

#ones() 모든 값을 1로 채운 ndarray 반환
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


ndarray의 차원과 크기를 변경하는 reshape()

In [4]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [6]:
#사이즈 안 맞으면 오류남
array1.reshape(4,3)

ValueError: ignored

In [7]:
#-1이용시 원래 ndarray와 호환되는 size로 변형
array1= np.arange(10)
print(array1)
array2 = array1.reshape(-1, 5)
print('array2 shape:', array2.shape)

array3 = array1.reshape(5, -1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [9]:
#4에 맞는 사이즈는 없기에 오류남
array1= np.arange(10)
array4=array1.reshape(-1,4)

ValueError: ignored

In [12]:
#reshape(-1,1) 이용 3->2->1차원 변경
array1=np.arange(8)

array3d=array1.reshape(2,2,2)
print('array3d:\n',array3d.tolist(),'\n')

# 3차원 ndarray를 2차원 ndarray로 변환
array5=array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape,'\n')

# 1차원 ndarray를 2차원 ndarray로 변환
array6=array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]] 

array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1) 

array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)
1. 특정한 데이터만 추출 : 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터가 반환됨.
2. 슬라이싱(Slicing) : 슬라이싱은 연속된 인덱스상의 ndarry를 추출하는 방식

  ':' 기호 사이에 시작 인덱스와 종료 인덱스를 표시하면 시작 인덱스에서 (종료 인덱스 -1) 위치에 있는 데이터의 ndarray를 반환

3. 팬시 인덱싱(Fancy indexing) : 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 잇는 데이터의 ndarray를 반환
4. 불린 인덱싱(Boolean indexing) : 특정 조건에 해당하는지 여부인 True/False 값 인덱싱 집합을 기반으로 True에 해당하는 인덱스 위치에 있는 데이터의 ndarray를 반환

In [13]:
#단일 값 추출-ndarray 객체에 해당하는 위히의 인덱스값을 []안에 입력
#1부터 9까지의 1차원 ndarray 생성
array1=np.arange(start=1,stop=10)
print('array1:',array1)

#index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값 의미
value=array1[2]
print('value:',value)
print(type(value))

print('맨 뒤의 값:',array1[-1],'맨 뒤에서 두 번째 값:',array1[-2],'\n')

# 단일 인덱스를 이용하여 ndarray내의 데이터 값을 수정
array1[0]=9
array1[8]=0
print('array1:',array1)

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>
맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8 

array1: [9 2 3 4 5 6 7 8 0]


In [14]:
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 0 맨 뒤에서 두 번째 값: 8


In [15]:
# 2차원
array1d=np.arange(1,10)
array2d=array1d.reshape(3,3)
print(array2d)

print('(row=0,col=0) index 가리키는 값 : ', array2d[0,0])
print('(row=0,col=1) index 가리키는 값 : ', array2d[0,1])
print('(row=1,col=0) index 가리키는 값 : ', array2d[1,0])
print('(row=2,col=2) index 가리키는 값 : ', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값 :  1
(row=0,col=1) index 가리키는 값 :  2
(row=1,col=0) index 가리키는 값 :  4
(row=2,col=2) index 가리키는 값 :  9


슬라이싱 ':'

In [17]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

array4=array1[:3]
print(array4)

array5=array1[3:]
print(array5)

array6=array1[:]
print(array6)

[1 2 3]
<class 'numpy.ndarray'>
[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [18]:
# 2차원 슬라이싱
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)
print('array2d:\n',array2d,'\n')

print('array2d[0:2,0:2]\n',array2d[0:2 , 0:2],'\n')
print('array2d[1:3,0:3]\n',array2d[1:3,0:3],'\n')
print('array2d[1:3,:]\n',array2d[1:3,:],'\n')
print('array2d[:,:]\n',array2d[:,:],'\n')
print('array2d[:2,1:]\n',array2d[:2,1:],'\n')
print('array2d[:2,0]\n',array2d[:2,0],'\n')


array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

array2d[0:2,0:2]
 [[1 2]
 [4 5]] 

array2d[1:3,0:3]
 [[4 5 6]
 [7 8 9]] 

array2d[1:3,:]
 [[4 5 6]
 [7 8 9]] 

array2d[:,:]
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

array2d[:2,1:]
 [[2 3]
 [5 6]] 

array2d[:2,0]
 [1 4] 



In [19]:
print(array2d[0]) # axis 0의 첫번째 row 반환
print(array2d[1]) # axis 0의 두번째 row 반환 
print('array2d[0] shape:',array2d[0].shape,'array2d[1] shape:',array2d[1].shape) # 1차원

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


팬시 인덱싱

In [20]:
array1d=np.arange(1,10)
array2d=array1d.reshape(3,3)

array3=array2d[[0,1],2]
print('array2d[[0,1],2] =>',array3.tolist())

array4=array2d[[0,1],0:2]
print('array2d[[0,1],0:2] =>',array4.tolist())

array5=array2d[[0,1]] 
print('array2d[[0,1]] =>',array5.tolist())

array2d[[0,1],2] => [3, 6]
array2d[[0,1],0:2] => [[1, 2], [4, 5]]
array2d[[0,1]] => [[1, 2, 3], [4, 5, 6]]


불린 인덱싱
- 조건 필터링과 검색 동시에 가능
1. array1d > 5 와 같이 ndarray의 필터링 조건을 [ ] 안에 기재
2.  False 값은 무시하고 True값에 해당하는 인덱스값만 저장 (유의해야 할 사항은 True값 자체인 1을 저장하는 것이 아니라 True값을 가진 인덱스를 저장한다는 것)
3. 저장된 인덱스 데이터 세트로 ndarray 조회

In [21]:
array1d=np.arange(1,10)
# []안에 array1d > 5 Boolean Indexing을 적용
array3=array1d[array1d>5]
print('array1d>5 불린 인덱싱 결과 값:',array3)


array1d>5 불린 인덱싱 결과 값: [6 7 8 9]


In [22]:
boolean_indexing=array1d>5
print(boolean_indexing)
print(array1d[boolean_indexing])

[False False False False False  True  True  True  True]
[6 7 8 9]


행렬의 정렬 - sort()와 argsort()

np.sort()- 원 행렬 그대로 유지한 채 원 행렬의 정렬된 행렬 반환
ndarray.sort() - 원 행렬 자체를 정렬한 형태로 반환

In [23]:
org_array=np.array([3,1,9,5])
print("원본 행렬:",org_array)

# np.sort()로 정렬
sort_array1=np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:',sort_array1) # 원본 행렬을 변경하지 않고 정렬된 형태로 반환/ default 오름차순
print('np.sort() 호출 후 원본 행렬:',org_array,'\n')

# ndarray.sort()로 정렬
sort_array2=org_array.sort()
print('org_array.sort() 호출 후 반환된 정렬 행렬:',sort_array2) # 원본 행렬 자체를 정렬된 값으로 변환/ default 오름차순
print('org_array.sort() 호출 후 원본 행렬:',org_array,'\n')

# 내림차순으로 정렬
sort_array1_desc=np.sort(org_array)[::-1]
print('내림차순으로 정렬:',sort_array1_desc)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5] 

org_array.sort() 호출 후 반환된 정렬 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9] 

내림차순으로 정렬: [9 5 3 1]


In [24]:
#행렬이 2차원 이상
array2d=np.array([[8,12],
                  [7,1]])
sort_array2d_axis0=np.sort(array2d,axis=0)
print('row 방향으로 정렬:\n',sort_array2d_axis0)

sort_array2d_axis1=np.sort(array2d,axis=1)
print('column 방향으로 정렬:\n',sort_array2d_axis1)

row 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
column 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


정렬된 행렬의 인덱스 반환

In [27]:
org_array=np.array([3,1,9,5])

sort_indices=np.argsort(org_array)
print(type(sort_indices)) # ndarray형
print('행렬 정렬 시 원본 행렬의 인덱스:',sort_indices)



<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [26]:
# 내림차순
sort_indices_desc=np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:',sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [28]:
import numpy as np
name_array=np.array(['John','Mike','Sarah','Kate','Samuel'])
score_array=np.array([78,95,84,98,88])

sort_indices_asc=np.argsort(score_array)
print('성적 오름차순 정렬 시 sort_array의 인덱스',sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:',name_array[sort_indices_asc])

성적 오름차순 정렬 시 sort_array의 인덱스 [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


선형대수 연산 - 행렬 내적과 전치 행렬 구하기

행렬 내적 np.dot()이용

전치 행렬 transpose()

In [29]:
A=np.array([[1,2,3],
           [4,5,6]])
B=np.array([[7,8],
            [9,10],
            [11,12]])
dot_product=np.dot(A,B)
print('행렬 내적 결과:\n',dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [30]:
# 전치 행렬
A=np.array([[1,2],
            [3,4]])
transpose_mat=np.transpose(A)
print('A의 전치행렬:\n',transpose_mat)

A의 전치행렬:
 [[1 3]
 [2 4]]
